name: Swift

on:
  push:
    branches: 
    - dev
    - feature/*
    - fix/*
    - refactor/*
    - test/*
  pull_request:
    branches:
    - dev
    - feature/*
    - fix/*
    - refactor/*
    - test/*
 
jobs:
  build:
    name: Build
    env:
      SCHEME: "MateRunner"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Build application
      run: |
        echo "$FCM_KEY" >> /Users/runner/work/iOS06-MateRunner/iOS06-MateRunner/MateRunner/MateRunner/Resource/Debug.xcconfig
        echo "$FCM_KEY" >> /Users/runner/work/iOS06-MateRunner/iOS06-MateRunner/MateRunner/MateRunner/Resource/Release.xcconfig
        pod install --repo-update --clean-install --project-directory=MateRunner
        xcodebuild test -workspace MateRunner/MateRunner.xcworkspace -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" | xcpretty --color --simple
