name: Swift

on:
  push:
    branches: 
    - dev
    - feature/*
    - fix/*
    - refactor/*
    - test/*
  pull_request:
    branches:
    - dev
    - feature/*
    - fix/*
    - refactor/*
    - test/*
 
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install --repo-update --clean-install --project-directory=MateRunner
    - name: Build
      run: |
          echo "$FCM_KEY" >> /Users/runner/work/iOS06-MateRunner/iOS06-MateRunner/MateRunner/MateRunner/Resource/Debug.xcconfig
          echo "$FCM_KEY" >> /Users/runner/work/iOS06-MateRunner/iOS06-MateRunner/MateRunner/MateRunner/Resource/Release.xcconfig
          xcodebuild -workspace MateRunner/MateRunner.xcworkspace -scheme MateRunner -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Test
      run: xcodebuild -workspace MateRunner/MateRunner.xcworkspace -scheme MateRunner -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
